services:
  postgres:
    image: postgres:15
    container_name: jarvis-db
    environment:
      POSTGRES_DB: jarvis
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
